// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VC.Recources.Infrastructure;

#nullable disable

namespace VC.Recources.Infrastructure.Migrations
{
    [DbContext(typeof(ResourceDbContext))]
    [Migration("20250318134912_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("resources")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VC.Recources.Resource.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Resources", "resources");
                });

            modelBuilder.Entity("VC.Recources.Resource.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("Skills", "resources");
                });

            modelBuilder.Entity("VC.Recources.Resource.Domain.Entities.Skill", b =>
                {
                    b.HasOne("VC.Recources.Resource.Domain.Entities.Resource", "Resource")
                        .WithMany("Skills")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("VC.Recources.Resource.Domain.Entities.Experience", "Expirience", b1 =>
                        {
                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Months")
                                .HasColumnType("integer");

                            b1.Property<int>("Years")
                                .HasColumnType("integer");

                            b1.HasKey("SkillId");

                            b1.ToTable("Skills", "resources");

                            b1.WithOwner()
                                .HasForeignKey("SkillId");
                        });

                    b.Navigation("Expirience")
                        .IsRequired();

                    b.Navigation("Resource");
                });

            modelBuilder.Entity("VC.Recources.Resource.Domain.Entities.Resource", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
